version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
      - mvn install -DskipTests

  build:
    commands:
      - echo Building the Spring Boot app...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`
      - ls -l target/
      - mv target/*.jar springboot-app.jar
      
artifacts:
  files:
    - springboot-app.jar
