version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - sudo yum install -y maven
  build:
    commands:
      - echo Building the Spring Boot app...
      - mvn clean package -DskipTests
artifacts:
  files:
    - target/*.jar
