version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Building the Spring Boot app...
      - mvn clean package -DskipTests
artifacts:
  files:
    - /tmp/codebuild/output/src780/src/s3/01/target/Exercise-1.0.2.jar.original
