version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Building the Spring Boot app...
      - mvn clean package -DskipTests
      - echo "Listing files in the target directory:"
      - ls -R target/
artifacts:
  files:
    - target/Exercise-1.0.2.jar.original
