version: '3.8'
services:
  db:
    image: postgres:16  # Official PostgreSQL image
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"  # Expose DB to host for tools like pgAdmin
    volumes:
      - db-data:/var/lib/postgresql/data  # Persist data locally
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d webapi"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: 124355640783.dkr.ecr.us-east-1.amazonaws.com/exercise-crud
    build:
      context: .
      dockerfile: Dockerfile  # Ensure Dockerfile exists
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/webapi
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
