spring.datasource.url=jdbc:postgresql://db:5432/webapi
spring.datasource.username=postgres

# PostgreSQL JDBC driver (optional in most cases)
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (JPA) settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.pattern.level=%5p [%X{correlationId}]
logging.file.name=/app/logs/exercise_crud.log



