# Hibernate Properties
spring.jpa.hibernate.ddl-auto=update

#spring.jpa.show-sql=true
logging.file.name=logs/exercise_crud.log
logging.level.org.js=DEBUG

management.endpoints.web.exposure.include=*


